workflows:
  android-debug:
    name: Android Debug Workflow
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    scripts:
      - name: Flutter get packages
        script: flutter pub get
      - name: Build Android APK
        script: flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
